import Link from "next/link";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { serif, sansSerif } from "./fonts";
import Image from "next/image";
import Divider from "./images/divider.svg";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-lightgray " + cn(serif.variable, sansSerif.variable)}>
        <header className="px-16">
          <div className="flex flex-row h-32">
            <div className="basis-1/5 content-center">
              <nav className="flex flex-row gap-6 justify-start">
                <Link className="font-serif text-base text-darkgray" href="/pages/about">about</Link>
                <Link className="font-serif text-base text-darkgray" href="/blog">blog</Link>
              </nav>
            </div>
            <Link className="basis-3/5 content-center text-center" href="/blog">
              <p className="font-serif text-darkgray text-4xl">musings from munich</p>
              <p className="font-sans-serif text-darkgray">
                random thoughts about photography, coffee and food
              </p>
            </Link>
            <div className="basis-1/5 content-center">
              <nav className="flex flex-row gap-6 justify-end">
                <Link className="font-serif text-base text-darkgray" href="/pages/contact">contact</Link>
                <Link className="font-serif text-base text-darkgray" href="/pages/imprint">imprint</Link>
              </nav>
            </div>
          </div>
          <div className="flex justify-center">
            <Image
              alt="line-divider"
              src={Divider}
              width={427}
              height={20}
            />
          </div>
        </header>
        <main className="p-16">
          <div className="flex flex-row">
            <div className="basis-1/5"></div>
            <div className="basis-3/5">
              {children}
            </div>
            <div className="basis-1/5"></div>
          </div>
        </main>
      </body>
    </html>
  );
}
